# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PremierSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PremierSwift

  target 'PremierSwiftTests' do
    pod 'SnapKit', '~> 5.0.0'
    # Pods for testing
  end

end
